[package]
name = "sode"
version = "0.1.3"
edition = "2024"
description = "A simple and small binary decoding / encoding crate"
readme = "README.md"
repository = "https://github.com/hatya-mouse/sode"
license = "MIT"
keywords = ["binary", "decoding", "encoding", "serialization", "deserialization"]

[dependencies]
